// <auto-generated />
using System;
using Agency.Data.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Agency.Data.Migrations
{
    [DbContext(typeof(AgencyDBContext))]
    [Migration("20220826173455_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Agency.Data.Models.Contracts.Journey", b =>
                {
                    b.Property<Guid>("JourneyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Distance")
                        .HasColumnType("int");

                    b.Property<string>("StartLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleID")
                        .HasColumnType("int");

                    b.HasKey("JourneyID");

                    b.ToTable("Journeys");

                    b.HasData(
                        new
                        {
                            JourneyID = new Guid("c7bdc365-7a0b-4c04-ff70-08da874aa142"),
                            Destination = "London",
                            Distance = 1518,
                            StartLocation = "Lovech",
                            VehicleID = 4
                        },
                        new
                        {
                            JourneyID = new Guid("00000000-7a0b-4c04-ff70-08da874aa142"),
                            Destination = "Huan Muan",
                            Distance = 2891,
                            StartLocation = "Sofia",
                            VehicleID = 3
                        });
                });

            modelBuilder.Entity("Agency.Data.Models.Contracts.Ticket", b =>
                {
                    b.Property<Guid>("TicketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AdministrativeCosts")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("JourneyID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TicketID");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            TicketID = new Guid("0000dc65-7a0b-4c04-ff70-08da874aa142"),
                            AdministrativeCosts = 200m,
                            JourneyID = new Guid("c7bdc365-7a0b-4c04-ff70-08da874aa142")
                        },
                        new
                        {
                            TicketID = new Guid("1000d365-7a0b-4c04-ff70-08da874aa142"),
                            AdministrativeCosts = 1200m,
                            JourneyID = new Guid("00000000-7a0b-4c04-ff70-08da874aa142")
                        });
                });

            modelBuilder.Entity("Agency.Data.Models.Vehicles.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleID"), 1L, 1);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PassangerCapacity")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerKilometer")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("VehicleID");

                    b.ToTable("Vehicles");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Vehicle");
                });

            modelBuilder.Entity("Agency.Data.Models.Vehicles.Models.Airplane", b =>
                {
                    b.HasBaseType("Agency.Data.Models.Vehicles.Models.Vehicle");

                    b.Property<bool>("HasFreeFood")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("Airplane");

                    b.HasData(
                        new
                        {
                            VehicleID = 4,
                            PassangerCapacity = 250,
                            PricePerKilometer = 2.9m,
                            Type = 1,
                            HasFreeFood = false
                        });
                });

            modelBuilder.Entity("Agency.Data.Models.Vehicles.Models.Boat", b =>
                {
                    b.HasBaseType("Agency.Data.Models.Vehicles.Models.Vehicle");

                    b.Property<bool>("OffersWaterSports")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("Boat");

                    b.HasData(
                        new
                        {
                            VehicleID = 1,
                            PassangerCapacity = 90,
                            PricePerKilometer = 4.1m,
                            Type = 2,
                            OffersWaterSports = true
                        });
                });

            modelBuilder.Entity("Agency.Data.Models.Vehicles.Models.Bus", b =>
                {
                    b.HasBaseType("Agency.Data.Models.Vehicles.Models.Vehicle");

                    b.HasDiscriminator().HasValue("Bus");

                    b.HasData(
                        new
                        {
                            VehicleID = 2,
                            PassangerCapacity = 15,
                            PricePerKilometer = 2.3m,
                            Type = 0
                        });
                });

            modelBuilder.Entity("Agency.Data.Models.Vehicles.Models.Train", b =>
                {
                    b.HasBaseType("Agency.Data.Models.Vehicles.Models.Vehicle");

                    b.Property<int>("Carts")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Train");

                    b.HasData(
                        new
                        {
                            VehicleID = 3,
                            PassangerCapacity = 100,
                            PricePerKilometer = 4m,
                            Type = 0,
                            Carts = 6
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
